apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstor-helm.fullname" . }}-backend
  labels:
    app: backend
  {{- include "bookstor-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.rollingUpdate.maxUnavailable | quote
        }}
    type: {{ .Values.backend.strategy.type | quote }}
  selector:
    matchLabels:
      app: backend
    {{- include "bookstor-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backend
      {{- include "bookstor-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MongoDBURL
          value: {{ quote .Values.backend.backend.env.mongodburl }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.backend.backend.image.repository }}:{{ .Values.backend.backend.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /ok
            port: 4001
          initialDelaySeconds: 2
          periodSeconds: 5
        name: backend
        ports:
        - containerPort: 4001
        readinessProbe:
          httpGet:
            path: /ok
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        resources: {}
      nodeSelector: {{- toYaml .Values.backend.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bookstor-helm.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.backend.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.backend.topologySpreadConstraints |
        nindent 8 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstor-helm.fullname" . }}-frontend
  labels:
    app: frontend
  {{- include "bookstor-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable | quote
        }}
    type: {{ .Values.frontend.strategy.type | quote }}
  selector:
    matchLabels:
      app: frontend
    {{- include "bookstor-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
      {{- include "bookstor-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "bookstor-helm.fullname" . }}-api-url
        image: {{ .Values.frontend.frontend.image.repository }}:{{ .Values.frontend.frontend.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.frontend.frontend.imagePullPolicy }}
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
      nodeSelector: {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bookstor-helm.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.frontend.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.frontend.topologySpreadConstraints
        | nindent 8 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstor-helm.fullname" . }}-mongo
  labels:
    app: mongo
  {{- include "bookstor-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      app: mongo
    {{- include "bookstor-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongo
      {{- include "bookstor-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongo.mongo.image.repository }}:{{ .Values.mongo.mongo.image.tag
          | default .Chart.AppVersion }}
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      nodeSelector: {{- toYaml .Values.mongo.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bookstor-helm.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.mongo.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.mongo.topologySpreadConstraints | nindent
        8 }}
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: {{ include "bookstor-helm.fullname" . }}-pvc
